project_id = "tkhgspegxyymfnypskqk"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.send-early-access-confirmation]
verify_jwt = false

[functions.submit-typeform]
verify_jwt = false

[functions.sync-to-hubspot]
verify_jwt = false
