[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate && npx prisma db push --accept-data-loss && npm run build"

[deploy]
startCommand = "node dist/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
